### ISSUE TITLE
Collection links

### ISSUE THREAD

**Issue by newsages** [spatie/laravel-resource-links#14]
Thx for package!!!

Have this controller:
index:
![imagen](https://user-images.githubusercontent.com/9095584/66275334-c7b0ea00-e887-11e9-899e-46d2daee7072.png)

ResourceCollection call Resource:
![imagen](https://user-images.githubusercontent.com/9095584/66275356-0e9edf80-e888-11e9-8ed6-930a64d92db9.png)

Resource:
![imagen](https://user-images.githubusercontent.com/9095584/66275365-2bd3ae00-e888-11e9-8396-8bc70dedf213.png)

How to make meta links?
_______________

Have Show, for mor detail data

show:
![imagen](https://user-images.githubusercontent.com/9095584/66275338-dac3ba00-e887-11e9-97e4-7a4022ed3330.png)

![imagen](https://user-images.githubusercontent.com/9095584/66275415-879e3700-e888-11e9-93bc-3d4acf2bb323.png)

**Comment by rubenvanassche** [comment]
Check out the meta helper: https://docs.spatie.be/laravel-resource-links/v1/usage/meta-helper/

**Comment by newsages** [comment]
ok, but dont work for me.

**Comment by freekmurze** [comment]
Please submit a failing test for us to look at.

**Comment by newsages** [comment]
OK, PR TestCase

**Comment by rubenvanassche** [comment]
Hi @newsages,

Thanks for the test in the PR, you're right, the meta section does not appear in your resource. Let me explain what's going on! The package is at this moment only build for singe resources(which still can be collections) but not for collection resources.

A piece of code might make it a bit more clear:

You can do following with the package

```php
return FakeResource::collection($testmodel)
```

But when using an external class for your resource collection, the meta section will not be shown:

```php
return new FakeResourceCollection($testmodel)
```

I've created a new issue, so this can be fixed: https://github.com/spatie/laravel-resource-links/issues/20

Thanks for your time and PR.

Ruben
