### ISSUE TITLE
Add support for resource collections

### ISSUE THREAD

**Issue by rubenvanassche** [spatie/laravel-resource-links#20]
The meta helper currently will work for resources if they are created as such:

```php
UserResource::collection($users);
```

But there is yet no support for dedicated resource collection classes:

```php
new UserResourceCollection($users);
```

**Comment by mludi** [comment]
You can use for now this as a workaround.

Override your `toArray` function in the UserResourceCollection with 

```

  public function toArray($request)
    {
        $this->collection->transform(function (User $user) {
            return (new UserResource($user));
        });

        return parent::toArray($request);
    }
```

**Comment by RossUK88** [comment]
Also would adding 

`public $collects = 'App\Http\Resources\User'; `

Not work instead of the above?

**Comment by edwinvdpol** [comment]
Nope :disappointed:

**Comment by reppair** [comment]
This would be a neat if Collections are supported.
