### ISSUE TITLE
ID on JSON output is incorrect

### ISSUE THREAD

**Issue by redenfm** [spatie/laravel-resource-links#22]
Good day!

This is a great package and perfect for my current project. But I'm having a problem with parsed links on JSON output.

Here's my web.php route file

```
Route::resource('stories', 'StoriesController');
```

On my app/Http/Resources/Story.php

```
namespace App\Http\Resources;

use App\Http\Controllers\StoriesController;
use Spatie\ResourceLinks\HasLinks;
use Illuminate\Http\Resources\Json\JsonResource;

class Story extends JsonResource
{
    use HasLinks;

    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'links' => $this->links(StoriesController::class)
        ];
    }
}
```
Here's the output:

![Capture](https://user-images.githubusercontent.com/25545971/67346864-c4e61280-f572-11e9-8a06-ef98d9a694d7.PNG)

BTW I'm using Laravel 6.

Thanks.

**Comment by rubenvanassche** [comment]
Hi @redenfm,

I had the same problem, the default boilerplate Laravel provides is not enough to fully deduce the parameters. I solved it by changing the functions in the controller.

This was the default


```php
public function show($id)
{
    dd($id);
}
```

And I changed it into

```php
public function show(User $user)
{
    dd($user);
}
```

As you can see, I changed:
- `$id` ➞ `$user`
- Added the `User` as type hint
